const images = {
  icons: {
      // user1: require('../assets/img/1.png'),
      // user2: require('../assets/images/user2.png'),
      // user3: require('../assets/images/user3.png'),
      // iPhone13: require('../assets/images/iPhone13.gif'),
      // landingPageMsg: require('../assets/images/msg.png'),
      // landingPageBook: require('../assets/images/book.png'),
      // landingPageCalender: require('../assets/images/calender.png'),
      // userIcon: require('../assets/images/ic_user_main.png'),
      // ellipse: require('../assets/images/ellipse.png'),
      // bookStore: require('../assets/images/bookStore.png'),
      // bookStore2: require('../assets/images/bookStore2.png'),
      // reviewHeader: require('../assets/images/reviewHeader.png'),
      // line_up: require('../assets/images/line_up.png'),
      // emoji1: require('../assets/images/emoji1.png'),
      // emoji2: require('../assets/images/emoji2.png'),
      // emoji3: require('../assets/images/emoji3.png'),
      // emoji4: require('../assets/images/emoji4.png'),
      // emoji5: require('../assets/images/emoji5.png'),
      // emoji6: require('../assets/images/emoji6.png'),
      // campusImage: require('../assets/images/campusImage.png'),
      // campusCategory1: require('../assets/images/campusCategory1.png'),
      // campusCategory2: require('../assets/images/campusCategory2.png'),
      // campusCategory3: require('../assets/images/campusCategory3.png'),
      // campusCategory4: require('../assets/images/campusCategory4.png'),
      // campusCategory5: require('../assets/images/campusCategory5.png'),
      // campusCategory6: require('../assets/images/campusCategory6.png'),
      // writeCampusPost: require('../assets/images/writeCampusPost.png'),
      // no_media: require('../assets/images/no_media.jpeg'),
      // playIcon:require('../assets/images/playIcon.png'),
  },
};

export default images;
