export default {
  VERSION: '1.0.0.001',

  BASE_URL: '',
  NEXT_PUBLIC_STATIC_URL_PREFIX: 'https://static.ranssul.com/',
  NEXT_PUBLIC_STATIC_URL_PREFIX_WITHOUT_SLASH: 'https://static.ranssul.com',
  NEXT_PUBLIC_WEBSITE_URL:'https://ranssul.com',

  GET_NOTIFICATIONS:'api/v1/notification',
  NEW_POST_UPLOAD: 'api/v1/posts',
  POST_IMAGE_UPLOAD: 'api/v1/upload',
  GET_POSTS:  'api/v1/posts',
  LOGIN: 'api/v1/auth/signin',
  GET_MAGORS:'api/v1/majors',
  GET_UNIVERSITIES: 'api/v1/university',
  USER_REGISTER: 'api/v1/user/register',
  VERIFY_OTP: 'api/v1/user/verifyOtp',
  SET_PASSWORD: 'api/v1/user/setPassword',
  RESEND_EMAIL: 'api/v1/user/resendEmail',
  COMMENTS: 'api/v1/comments',
  GET_UNIVERSITY: 'api/v1/university',
  CALENDERS: 'api/v1/calendars/userSwipper',
  GET_CLASSES: 'api/v1/calendars/user',
  CALENDERS_EVENT: 'api/v1/calendars',
  GET_SCHOOL: 'api/v1/schools',
  GET_DEPARTMENTS: 'api/v1/departments',
  GET_LECTURES: 'api/v1/lectures',
  GET_FAVORITES: 'api/v1/tags/favorite',
  GET_MY_POSTS: 'api/v1/myposts',
  GET_CAMPUS_POSTS: 'api/v1/campusposts',
  FORGOT_PW: 'api/v1/user/forgotpassword',
  VERIFY_OTP_FORGOT_PW: 'api/v1/user/verifyOtpForgotpassword',
  GET_FRIENDS: 'api/v1/getFriendList',
  SEND_FRIEND_REQUEST: 'api/v1/sendFriendRequest',
  ACCEPT_OR_REJECT_REQUEST: 'api/v1/acceptRejectFriendRequest',
  GET_FRIENDS_REQUESTS: 'api/v1/friendRequest',
  GET_FRIENDS_LIST: 'api/v1/getFriendListData',
  // : '/api/v1/posts?region=UCLA&regionUniversity=&sort=monthly'
}